add Catalog with Image, Price and TextBox
pedrogabriel69/react_app pull request #2
Opened 2018-07-20 21:13 UTC by pedrogabriel69

2018-07-21 13:20 UTC, erisnuts requested changes

2018-07-21 13:20 UTC, erisnuts commented on .gitignore
> +dist/*
исправить так, чтобы dist не попадал в коммит

2018-07-21 13:20 UTC, erisnuts commented on src/components/Catalog.js
> +      <div className="Catalog">
разделить контейнерную и презентационную логику

2018-07-21 13:20 UTC, erisnuts commented on .gitignore
> +dist/*
и добавить yarn.lock

2018-07-21 13:20 UTC, erisnuts commented on src/components/ProductCard.js
> +        <Image src={product.image.imageUrl} alt={product.image.imageContext} height={product.image.imageHeight} width={product.image.imageWidth} />
здесь уместно деструктурирование объекта product.image
`const { imageUrl, ... } = product.image`

2018-07-24 08:33 UTC, erisnuts requested changes

2018-07-24 08:33 UTC, erisnuts commented on src/containers/CatalogPage.js
> +      <div className="catalog-page">
разделить контейнерную и презентационную логику

2018-07-24 08:33 UTC, erisnuts commented on src/containers/CatalogPage.js
> +    this.setState ({ products: PRODUCTS });
setState в методе componentDidMount будет инициировать лишний ре-рендер, может возникнуть рекурсия. в данном случае данные следует копировать в состояние компонента в конструкторе.

2018-07-26 07:47 UTC, index01d approved these changes

2018-07-26 07:47 UTC, index01d commented on .gitignore
> +dist/*
yarn.lock в игнор не нужно

2018-07-27 02:46 UTC, merged